nuget:
  account_feed: true
  project_feed: true

before_build:
  nuget restore

after_test:
  - cmd: nuget pack Package.nuspec
  - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
